name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "hey there!, thank you for creating a new issue in this repository. i appreciate your contribution!!"
        pr-message: "hey there!, thank you for creating a new Pull Requests in this repository. i appreciate your contribution!!"
